version: '3.8'

services:
  backend:
    image: ghcr.io/gauvainthery/naubion-backend:latest
    container_name: naubion-backend
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
    volumes:
      # Mount environment file if it exists
      - .env:/app/.env:ro
    networks:
      - naubion-network
    healthcheck:
      test: ['CMD', 'node', 'dist/healthcheck.js']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    image: ghcr.io/gauvainthery/naubion-frontend:latest
    container_name: naubion-frontend
    ports:
      - '3000:80'
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - naubion-network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:80',
          '||',
          'exit',
          '1'
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy

networks:
  naubion-network:
    driver: bridge

volumes:
  node_modules:
