# Docker Compose for Naubion
services:
  backend:
    image: ghcr.io/gauvainthery/naubion-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
      platforms:
        - linux/amd64
    container_name: naubion-backend
    ports:
      - '${BACKEND_PORT:-8080}:8080'
    environment:
      # Core application settings - Production defaults
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=8080
      - HOST=0.0.0.0
      - LOG_LEVEL=${LOG_LEVEL:-warn}
      # Node.js memory optimization for low-memory systems
      - NODE_OPTIONS=--max-old-space-size=400

      # CORS configuration
      - CORS_ORIGIN=${CORS_ORIGIN}

      # Database configuration
      - DB_HOST=database
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE:-false}
      - DB_LOGGING=false

      # Cache configuration
      - CACHE_ANALYSIS_RESULTS=${CACHE_ANALYSIS_RESULTS:-true}
      - CACHE_TTL_HOURS=${CACHE_TTL_HOURS:-240}

      # Puppeteer configuration
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - BROWSER_HEADLESS=true
      - BROWSER_TIMEOUT=${BROWSER_TIMEOUT:-120000}

      # Chrome configuration optimized for Docker
      - CHROME_BIN=/usr/bin/chromium-browser
      - CHROME_PATH=/usr/bin/chromium-browser
      - CHROME_CRASHPAD_DISABLED=1
      - CHROME_CACHE_DIR=/home/naubion/.cache/chromium
      - CHROME_CONFIG_DIR=/home/naubion/.config/chromium
      - DISPLAY=:99
      - NO_SANDBOX=true
      - DISABLE_DEV_SHM_USAGE=true

      # Analysis Configuration
      - MAX_CONCURRENT_ANALYSIS=${MAX_CONCURRENT_ANALYSIS:-10}
      - ANALYSIS_TIMEOUT=${ANALYSIS_TIMEOUT:-300000}
      - ANALYSIS_RETRIES=${ANALYSIS_RETRIES:-3}

      # External services
      - MAILJET_API_KEY=${MAILJET_API_KEY}
      - MAILJET_API_SECRET=${MAILJET_API_SECRET}
      - MAILJET_CONTACT_LIST_ID=${MAILJET_CONTACT_LIST_ID}

      # Admin configuration
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

    env_file:
      - .env

    # Production resource limits - Increased memory for Puppeteer
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.3'
          memory: 300M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

    # Security and performance optimizations for Puppeteer
    security_opt:
      - no-new-privileges:true
    cap_add:
      - SYS_ADMIN # Required for Chrome in some cases
    shm_size: '256m' # Increase shared memory for Chrome
    read_only: true
    tmpfs:
      - /tmp:size=512M,exec
      - /app/logs
      - /dev/shm:size=256M # Additional shared memory for Chrome
      - /home/naubion/.cache:size=256M,uid=1001,gid=1001 # Chrome cache directory (increased size)
      - /home/naubion/.config:size=128M,uid=1001,gid=1001 # Chrome config directory
    networks:
      - naubion-network
    healthcheck:
      test: ['CMD', 'node', 'apps/backend/dist/healthcheck.js']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    container_name: naubion-database
    environment:
      - POSTGRES_DB=${DB_DATABASE:-naubion}
      - POSTGRES_USER=${DB_USERNAME:-naubion}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-naubion_password}
      # Memory optimization for low-memory systems
      - POSTGRES_SHARED_BUFFERS=32MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=64MB
      - POSTGRES_WORK_MEM=2MB
      - POSTGRES_MAINTENANCE_WORK_MEM=16MB
    volumes:
      - postgres_data:/var/lib/postgresql/data

    # Memory limits for database
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 64M

    networks:
      - naubion-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME:-naubion} -d ${DB_DATABASE:-naubion}']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  frontend:
    image: ghcr.io/gauvainthery/naubion-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_APP_NAME=naubion
        - VITE_ENABLE_ANALYTICS=true
    container_name: naubion-frontend
    ports:
      - '${FRONTEND_PORT:-80}:80'
      - '${FRONTEND_SSL_PORT:-443}:443'
    volumes:
      # Mount SSL certificates
      - ./ssl/certs:/etc/ssl/certs:ro
      - ./ssl/private:/etc/ssl/private:ro

    # Production resource limits
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 64M

    # Production security hardening
    security_opt:
      - no-new-privileges:true
    # read_only: true  # Disabled for nginx compatibility
    # tmpfs:
    #   - /tmp:uid=1001,gid=1001
    #   - /var/cache/nginx:uid=1001,gid=1001
    #   - /var/run:uid=1001,gid=1001
    networks:
      - naubion-network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:80',
          '||',
          'exit',
          '1'
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      - backend
      - database

networks:
  naubion-network:
    driver: bridge

volumes:
  postgres_data:
